# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pnJYp78-tOO2AFH5mgfz8L485tDBAK3p
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

np.random.seed(42)

num_patients = 10000

data = pd.DataFrame({
    'Patient_ID': range(1, num_patients + 1),
    'Age': np.random.randint(20, 81, num_patients),
    'Gender': np.random.choice(['Male', 'Female'], num_patients),
    'Blood_Pressure': np.random.randint(80, 181, num_patients),
    'Sugar_Level': np.random.randint(70, 201, num_patients),
    'Cholesterol': np.random.randint(150, 301, num_patients),
    'Heart_Rate': np.random.randint(60, 121, num_patients)
})
data

print("\nMissing Values:\n", data.isnull().sum())
print("\nData Types:\n", data.dtypes)

def risk_level(row):
    score = 0

    if row['Blood_Pressure'] > 140:
        score += 1
    if row['Sugar_Level'] > 140:
        score += 1
    if row['Cholesterol'] > 240:
        score += 1
    if row['Heart_Rate'] > 100:
        score += 1

    if score >= 3:
        return 'High'
    elif score == 2:
        return 'Medium'
    else:
        return 'Low'

data['Risk_Level'] = data.apply(risk_level, axis=1)

bins = [20, 35, 50, 65, 80]
labels = ['Young', 'Adult', 'Mid-Age', 'Senior']
data['Age_Group'] = pd.cut(data['Age'], bins=bins, labels=labels)
print(bins)
print(labels)
print(data)

print("Descriptive Statistics:", data.describe())

high_risk = data[data['Risk_Level'] == 'High']
print("High Risk Patients Count:", len(high_risk))

age_risk = pd.crosstab(data['Age_Group'], data['Risk_Level'])
print("Age Group vs Risk:", age_risk)

gender_analysis = data.groupby('Gender')[['Blood_Pressure','Sugar_Level','Cholesterol','Heart_Rate']].mean()
print("Gender-wise Analysis:", gender_analysis)

risk_dist = data['Risk_Level'].value_counts()
print("Risk Distribution:", risk_dist)

plt.figure(figsize=(18,12))

plt.subplot(2,3,1)
plt.hist(data['Blood_Pressure'], bins=20)
plt.title("Blood Pressure Distribution")

plt.subplot(2,3,2)
risk_dist.plot(kind='pie', autopct='%1.1f%%')
plt.title("Risk Level Distribution")

plt.subplot(2,3,3)
age_risk.plot(kind='bar', stacked=True)
plt.title("Age Group vs Risk Level")

plt.subplot(2,3,4)
plt.scatter(data['Age'], data['Blood_Pressure'])
plt.xlabel("Age")
plt.ylabel("Blood Pressure")
plt.title("Blood Pressure vs Age")

plt.subplot(2,3,5)
sns.boxplot(data=data[['Blood_Pressure','Sugar_Level','Cholesterol','Heart_Rate']])
plt.title("Outlier Detection")
plt.tight_layout()
plt.show()

plt.figure(figsize=(6,5))
sns.heatmap(data[['Age','Blood_Pressure','Sugar_Level','Cholesterol','Heart_Rate']].corr(), annot=True)
plt.title("Correlation Heatmap")
plt.show()

print("\n--- Insights ---")
print("1. Older patients tend to have higher blood pressure.")
print("2. High sugar and cholesterol increase risk levels.")
print("3. High-risk patients require immediate attention.")
print("4. Some outliers detected in vital parameters.")
print("5. Risk level varies across age groups.")